"""The timeline tables.

Three things Django cannot write itself, as raw SQL:

* ``postgis``, for the generated ``geom`` columns. Created here, not only in the deployment's
  database, because the test database is built from template1.
* ``timeline_change_seq``, the sequence every ``received_at`` stamp is drawn from. First,
  because the tables default to it.
* ``timeline_point``, partitioned by month of ``ts``. Postgres requires every unique key of a
  partitioned table to contain the partition key, so the primary key is ``(id, ts)`` and the
  upsert key ``(device_id, client_id, ts)``. There is no DEFAULT partition: one that already
  held a month's rows would block creating that month's partition. Partitions are created on
  demand by :func:`timeline.partitions.ensure_point_partitions`. Indexes declared on the
  parent are created on every partition. ``device_id`` carries no foreign key: Django's test
  flush truncates ``timeline_device`` without CASCADE and does not know this (unmanaged)
  table, so a constraint would make every flush fail; the backup code deletes a device's
  points before the device.
"""

import django.contrib.postgres.indexes
import django.db.models.deletion
import timeline.geo
import timeline.models
from django.conf import settings
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


POINT_TABLE = """
CREATE TABLE timeline_point (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    device_id bigint NOT NULL,
    client_id varchar(255) NOT NULL,
    ts timestamptz NOT NULL,
    lat double precision NOT NULL,
    lon double precision NOT NULL,
    geom geometry(Point,4326) GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(lon, lat), 4326)) STORED,
    acc double precision,
    speed double precision,
    heading double precision,
    alt double precision,
    received_at bigint NOT NULL DEFAULT nextval('timeline_change_seq'),
    PRIMARY KEY (id, ts),
    CONSTRAINT timeline_point_unique UNIQUE (device_id, client_id, ts)
) PARTITION BY RANGE (ts);
CREATE INDEX tl_point_user_stamp ON timeline_point (user_id, received_at);
CREATE INDEX tl_point_device_ts ON timeline_point (device_id, ts);
CREATE INDEX tl_point_geom ON timeline_point USING gist (geom);
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateExtension("postgis"),
        migrations.RunSQL(
            "CREATE SEQUENCE timeline_change_seq AS bigint",
            "DROP SEQUENCE timeline_change_seq",
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=255)),
                ('ts', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('geom', models.GeneratedField(db_persist=True, expression=timeline.geo.MakePoint(models.F('lon'), models.F('lat')), output_field=timeline.geo.GeometryPointField())),
                ('acc', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('alt', models.FloatField(blank=True, null=True)),
                ('received_at', models.BigIntegerField(db_default=timeline.models.NextStamp(), help_text='The change stamp (sequence, not time) the changes cursor pages through.')),
            ],
            options={
                'db_table': 'timeline_point',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text="The token's client_device claim.", max_length=2000)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_upload_at', models.DateTimeField(blank=True, help_text='When this device last wrote anything.', null=True)),
                ('segments_from', models.DateTimeField(blank=True, help_text="The `from` of this device's last replaceSegments.", null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lokate_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('geom', models.GeneratedField(db_persist=True, expression=timeline.geo.MakePoint(models.F('lon'), models.F('lat')), output_field=timeline.geo.GeometryPointField())),
                ('radius', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(help_text="The phone's edit time; last write wins on it.")),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Set on a tombstone.', null=True)),
                ('received_at', models.BigIntegerField(db_default=timeline.models.NextStamp(), help_text='The change stamp (sequence, not time) the changes cursor pages through.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Retention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lokate_retention', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('from_visit', models.CharField(blank=True, help_text='The client id of the visit it left.', max_length=255, null=True)),
                ('to_visit', models.CharField(blank=True, help_text='The client id of the visit it arrived at.', max_length=255, null=True)),
                ('distance', models.FloatField(help_text='Meters.')),
                ('mode', models.CharField(choices=[('WALK', 'Walk'), ('BIKE', 'Bike'), ('VEHICLE', 'Vehicle'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=16)),
                ('received_at', models.BigIntegerField(db_default=timeline.models.NextStamp(), help_text='The change stamp (sequence, not time) the changes cursor pages through.')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='timeline.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('geom', models.GeneratedField(db_persist=True, expression=timeline.geo.MakePoint(models.F('lon'), models.F('lat')), output_field=timeline.geo.GeometryPointField())),
                ('radius', models.FloatField()),
                ('point_count', models.IntegerField()),
                ('place_client_id', models.CharField(blank=True, help_text='The client id of the place this visit was matched to.', max_length=255, null=True)),
                ('received_at', models.BigIntegerField(db_default=timeline.models.NextStamp(), help_text='The change stamp (sequence, not time) the changes cursor pages through.')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='timeline.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, help_text="The reading token's client_device claim.", max_length=2000, null=True)),
                ('client_id', models.CharField(blank=True, help_text="The reading token's OAuth client.", max_length=2000, null=True)),
                ('operation', models.CharField(max_length=100)),
                ('range', models.CharField(blank=True, default='', help_text='What was read, e.g. a cursor span.', max_length=500)),
                ('rows', models.IntegerField(default=0, help_text='How many rows the read returned.')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-at'], name='tl_accesslog_user_at')],
            },
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='timeline_device_unique'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['user', 'received_at'], name='tl_place_user_stamp'),
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('user', 'client_id'), name='timeline_place_unique'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['user', 'received_at'], name='tl_trip_user_stamp'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['device', 'start'], name='tl_trip_device_start'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('device', 'client_id'), name='timeline_trip_unique'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['user', 'received_at'], name='tl_visit_user_stamp'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['device', 'start'], name='tl_visit_device_start'),
        ),
        migrations.AddConstraint(
            model_name='visit',
            constraint=models.UniqueConstraint(fields=('device', 'client_id'), name='timeline_visit_unique'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='tl_visit_geom'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geom'], name='tl_place_geom'),
        ),
        migrations.RunSQL(
            POINT_TABLE,
            "DROP TABLE timeline_point",
        ),
    ]
