# Generated by Django 6.0.6 on 2026-09-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accesslog',
            name='tl_accesslog_user_at',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='user',
        ),
        migrations.DeleteModel(
            name='Retention',
        ),
        migrations.DeleteModel(
            name='AccessLog',
        ),
    ]
